<a href="https://colab.research.google.com/github/LokeshDaga/ML_Assignment/blob/master/Assignment0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
print(sys.version);

3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]


In [ ]:
import sys
for p in sys.path:
   print(p)


/env/python
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages/IPython/extensions
/root/.ipython


In [ ]:
import inspect, os
print(inspect.getfile(inspect.currentframe()))
print(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))))


<ipython-input-21-999536cf70d4>
/content


In [ ]:
import numpy as np
A=np.random.randint(100000, size=(2, 3))
B= np.random.randint(10000, size=(3, 2))
print(A)
print(B)
C=A.dot(B)
print(C)

[[8 1 9]
 [8 7 2]]
[[6 1]
 [0 0]
 [5 9]]
[[93 89]
 [58 26]]


In [ ]:
import numpy as np
C=0
for i in range(0,5):
 A=np.random.randint(1000, size=(2, 3))
 B= np.random.randint(1000, size=(3, 2))
 C=C+A.dot(B)
 
print(C/5)

[[1117516.4  772925.4]
 [1110159.4  785784.8]]


In [ ]:
#import pandas as pd
np.savetxt('test.csv',C/5,delimiter=',')
#C=pd.read_csv('test.csv', sep=',',header=None)
C= np.genfromtxt('test.csv', delimiter=',')
print(C.transpose())

[[2.54279578 2.05304115]
 [2.15424154 1.88386304]]


In [ ]:
from scipy import stats
C=C/5
print(C)
mean = np.mean(C)
median = np.median(C)
mode=stats.mode(C)
print('Mean is ',mean)
print('Median is ',median)
print('Mode is ',mode[0])

[[0.10171183 0.08616966]
 [0.08212165 0.07535452]]
Mean is  0.08633941503999999
Median is  0.08414565376
Mode is  ModeResult(mode=array([[0.08212165, 0.07535452]]), count=array([[1, 1]]))


In [ ]:

S=np.triu(C)
print(S)

[[2.54279578 2.15424154]
 [0.         1.88386304]]


In [ ]:
import csv 
n=input("Enter the number of coloumns:")
a=[]
for i in range(0,int(n)):
 a.append(int(input("Enter Coloumn number:")))
with open("test.csv", "r") as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for lines in csv_reader:
      print(lines)


Enter the number of coloumns:2
Enter Coloumn number:0
Enter Coloumn number:1
['2.542795775999999730e+00', '2.154241535999999790e+00']
['2.053041152000000036e+00', '1.883863040000000266e+00']


In [ ]:
A=[[1,2,3],[4,5,6]]
np.savetxt('nba.csv',A,delimiter=',')

In [ ]:
import pandas as pd  
s=input("Enter the number")
df = pd.read_csv("nba.csv")
df.replace(to_replace =int(s), 
                 value ="A")
print(df[0:])
np.savetxt('nba.csv',df,delimiter=',')




Enter the number2
   1.000000000000000000e+00  2.000000000000000000e+00  3.000000000000000000e+00
0                       4.0                       5.0                       6.0
