<a href="https://colab.research.google.com/github/LokeshDaga/ML_Assignment/blob/master/ML_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Part1-1

import numpy as np
array0=np.zeros(10)
print(array0)
print("\n")

array1=np.ones(10)
print(array1)
print("\n")

array5=np.ones(10)*5
print(array5)





[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#Part1-2

array = np.arange(10,51,2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#Part1-3

rarray = np.random.rand(3,2) 
print("Second array\n", rarray)



Second array
 [[0.29289111 0.54369618]
 [0.83926655 0.97751066]
 [0.34473536 0.01582053]]


In [ ]:
#Mounting google drive to save future files
from google.colab import drive
drive.mount('/drive')



Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).


In [ ]:
#Part1-4



np.savetxt('/drive/My Drive/Colab Notebooks/lab1/part1-3.txt', rarray, fmt="%0.8f") 
print("After loading, content of the text file:")

result = np.loadtxt('/drive/My Drive/Colab Notebooks/lab1/part1-3.txt')
print(result)




After loading, content of the text file:
[[0.29289111 0.54369618]
 [0.83926655 0.97751066]
 [0.34473536 0.01582053]]


In [ ]:
#Part2-1

from PIL import Image
import numpy as np
import pandas as pd

imframe = Image.open('/drive/My Drive/Colab Notebooks/lab1/image.png')
npframe = np.array(imframe.getdata())
df = pd.DataFrame(npframe)
df
df.to_csv("/drive/My Drive/Colab Notebooks/lab1/image.csv")







In [ ]:
#part2-2

df = pd.read_csv ("/drive/My Drive/Colab Notebooks/lab1/image.csv")
#df with all rows and column
print(df)
print("\n")



df.drop(df.tail(1).index,inplace=True)
df.drop(df.columns[len(df.columns)-1], axis=1, inplace=True)

print(df)



        Unnamed: 0    0    1    2
0                0  252  253  255
1                1  252  253  255
2                2  252  253  255
3                3  252  253  255
4                4  252  253  255
...            ...  ...  ...  ...
249995      249995  254  255  255
249996      249996  254  255  255
249997      249997  254  255  255
249998      249998  254  255  255
249999      249999  254  255  255

[250000 rows x 4 columns]


        Unnamed: 0    0    1
0                0  252  253
1                1  252  253
2                2  252  253
3                3  252  253
4                4  252  253
...            ...  ...  ...
249994      249994  254  255
249995      249995  254  255
249996      249996  254  255
249997      249997  254  255
249998      249998  254  255

[249999 rows x 3 columns]


In [ ]:
#part2-3
import pandas as pd
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2020-08-23 00:00:00


In [ ]:
#part3

from datetime import date 

def calculateAge(born): 
	today = date.today() 
	try: 
		birthday = born.replace(year = today.year) 


	except ValueError: 
		birthday = born.replace(year = today.year, 
				month = born.month + 1, day = 1) 

	if birthday > today: 
		return today.year - born.year - 1
	else: 
		return today.year - born.year 
		

print(calculateAge(date(1997, 2, 3)), "years") 


23 years
